FROM python:3.8

# Directorio de trabajo en el contenedor
WORKDIR /app/backend


# Copiar el proyecto Django al contenedor
COPY requirements.txt /app/backend

# Print contents of the directory
RUN ls -l /app/backend

# Instalar dependencias
RUN pip install -r requirements.txt

# Add the rest of the code
COPY . /app/backend

# Make port 8000 available for the app
EXPOSE 8000

# Be sure to use 0.0.0.0 for the host within the Docker container,
# otherwise the browser won't be able to find it
# CMD python3 manage.py runserver 0.0.0.0:8000





